/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_discord_bot;

import java_discord_bot.discord_bot.DiscordBot;


public class App {
    private static String greeting = "Hello, world";

    public static String getGreeting() {
        return greeting; 
    }

    public static void main(String[] args) {
        DiscordBot discordBot = new DiscordBot();
        discordBot.run();
        
        System.out.println(getGreeting());
    }
}
