/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_discord_bot;

import java_discord_bot.discord_bot.DiscordBot;


public class App {
    public static String getGreeting() {
        return "Starting Bot"; 
    }

    public static void main(String[] args) {
        DiscordBot discordBot = new DiscordBot("Add Bot Token Here");
        discordBot.run();
        
        System.out.println(getGreeting());
    }
}
